// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformManagementConsole.Contexts;

namespace PlatformManagementConsole.Migrations
{
    [DbContext(typeof(PmcDbContext))]
    [Migration("20200209134842_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PlatformManagementConsole.Models.Forms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Html");

                    b.Property<string>("JsonForm");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PlatformManagementConsole.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Image");

                    b.Property<string>("Link");

                    b.Property<string>("LinkTitle");

                    b.Property<int>("LinkType");

                    b.Property<DateTime>("MsgExp");

                    b.Property<int>("MsgFormat");

                    b.Property<string>("MsgHtml");

                    b.Property<string>("MsgJson");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PlatformManagementConsole.Models.Resolver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceType");

                    b.Property<string>("Guid");

                    b.Property<bool>("IsOnline");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<string>("OEM");

                    b.Property<string>("OsVersion");

                    b.Property<string>("Platform");

                    b.HasKey("Id");

                    b.ToTable("Resolvers");
                });

            modelBuilder.Entity("PlatformManagementConsole.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("session_name");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
