// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformManagementConsole.Contexts;

namespace PlatformManagementConsole.Migrations
{
    [DbContext(typeof(PmcDbContext))]
    partial class PmcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PlatformManagementConsole.Models.Resolver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceType");

                    b.Property<string>("Guid");

                    b.Property<bool>("IsOnline");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<string>("OEM");

                    b.Property<string>("OsVersion");

                    b.Property<string>("Platform");

                    b.HasKey("Id");

                    b.ToTable("Resolvers");
                });
#pragma warning restore 612, 618
        }
    }
}
